//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKitapProjesi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReviews
    {
        public int KitapID { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> Puan { get; set; }
        public string Yorum { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kitaplar Kitaplar1 { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        public virtual Kullanicilar Kullanicilar2 { get; set; }
    }
}
