//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKitapProjesi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.BookReviews = new HashSet<BookReviews>();
            this.BookReviews1 = new HashSet<BookReviews>();
        }
    
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public Nullable<System.DateTime> BasimTarihi { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<int> DurumID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookReviews> BookReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookReviews> BookReviews1 { get; set; }
        public virtual KitapTurleri KitapTurleri { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
        public virtual Durumlar Durumlar { get; set; }
    }
}
